---
title: "restaurant"
author: "Guangling Xu"
date: "2019/11/17"
output: html_document
---
```{r}
library(tidyverse)
library(plotly)
library(rvest)
library(readr)
library(viridis)
library(leaflet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
data_2018 = 
  read_csv("./data/2018data.csv") %>% 
  janitor::clean_names() 
newnames = colnames(data_2018) %>% 
  str_replace("number_of_","") 
names(data_2018) = newnames

tidy_data = 
data_2018 %>% 
  mutate(
    date_complete = date 
  ) %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  separate(time, into = c("hour", "minute"), sep = ":") %>%
  select(-zip_code, -location, -on_street_name, -cross_street_name, -off_street_name,-collision_id,-year) %>% 
  rename("vehicle_type" = "vehicle_type_code_1") %>% 
  mutate( day = as.numeric(day),
          month = as.numeric(month),
          hour = as.numeric(hour),
          minute = as.numeric(minute),
          latitude = replace_na(latitude,0),
          vehicle_type = str_to_lower(vehicle_type)
  ) %>%
  filter( latitude != 0) %>% 
  drop_na(borough)
```


```{r}
res = 
  read_csv("./large_data/nyc_inspec.csv") %>% 
  janitor::clean_names() 
```


```{r}
res_filter= res %>% 
  select(dba, boro, zipcode) %>% 
  drop_na()
res_filter = plyr::rename(res_filter, c("boro" = "borough"))

res_count = res_filter%>% 
  group_by(zipcode, borough) %>% 
  summarise(
    res_count = n()
  ) %>% 
  mutate(
    borough = toupper(borough)
  )


data_location = data_2018 %>% 
filter(zip_code != "NA", location != "NA") %>% 
select(borough, collision_id, zip_code, location, contributing_factor_vehicle_1, contributing_factor_vehicle_2, contributing_factor_vehicle_3, contributing_factor_vehicle_4, contributing_factor_vehicle_5) %>% 
  filter(
contributing_factor_vehicle_1 == "Alcohol Involvement"|
contributing_factor_vehicle_2 == "Alcohol Involvement"| contributing_factor_vehicle_3 == "Alcohol Involvement"| contributing_factor_vehicle_4 == "Alcohol Involvement"| contributing_factor_vehicle_5 == "Alcohol Involvement")
data_location = plyr::rename(data_location, c("zip_code" = "zipcode"))


acci_count = data_location %>% 
  group_by(zipcode, borough) %>% 
  summarise(
    acci_count = n()
  )
```  

```{r}
res_acci_count = left_join(acci_count, res_count, by = "zipcode") %>%
  select(-borough.y) %>% 
   plyr::rename(c("borough.x" = "borough")) %>% 
  mutate(
     location = recode(zipcode,  `10460` = "Central Bronx",`10453` = "Central Bronx",`10457` = "Central Bronx",
`10458` = "Bronx Park and Fordham",`10467` = "Bronx Park and Fordham",`10468` = "Bronx Park and Fordham",
`10451` = "High Bridge and Morrisania",`10452` = "High Bridge and Morrisania",`10456` = "High Bridge and Morrisania",
`10454` = "Hunts Point and Mott Haven",`10455` = "Hunts Point and Mott Haven",`10459` = "Hunts Point and Mott Haven",`10474` = "Hunts Point and Mott Haven",
`10463` = "Kingsbridge and Riverdale",`10471` = "Kingsbridge and Riverdale",
`10466` = "Northeast Bronx",`10469` = "Northeast Bronx",`10470` = "Northeast Bronx",`10475` = "Northeast Bronx",
`10475` = "Southeast Bronx",`10475` = "Southeast Bronx",`10475` = "Southeast Bronx",`10475` = "Southeast Bronx",`10475` = "Southeast Bronx",`10475` = "Southeast Bronx",
`11212` = "	Central Brooklyn",`11213` = "	Central Brooklyn",`11216` = "	Central Brooklyn",`11233` = "	Central Brooklyn",`11238` = "	Central Brooklyn",
`11209` = "	Southwest Brooklyn",`11214` = "	Southwest Brooklyn",`11228` = "Southwest Brooklyn",
`11204` = "	Borough Park",`11218` = "	Borough Park",`11219` = "	Borough Park",`11230` = "	Borough Park",
`11234` = "	Canarsie and Flatlands",`11236` = "	Canarsie and Flatlands",`11239` = "Canarsie and Flatlands",
`11223` = "Southern Brooklyn",`11224` = "Southern Brooklyn",`11229` = "Southern Brooklyn",`11235` = "Southern Brooklyn",
`11201` = "Northwest Brooklyn",`11205` = "Northwest Brooklyn",`11215` = "Northwest Brooklyn",`11217` = "Northwest Brooklyn",`11231` = "Northwest Brooklyn",
`11203` = "Flatbush",`11210` = "Flatbush",`11225` = "Flatbush",`11226` = "Flatbush",
`11207` = "East New York and New Lots",`11208` = "East New York and New Lots",
`11211` = "Greenpoint",`11212` = "Greenpoint",
`11220` = "Sunset Park",`11232` = "Sunset Park",
`11206` = "Bushwick and Williamsburg",`11221` = "Bushwick and Williamsburg",`11237` = "Bushwick and Williamsburg",
`10026` = "	Central Harlem",`10027` = "	Central Harlem",`10030` = "	Central Harlem",`10037` = "	Central Harlem",`10039` = "Central Harlem",
`10001` = "	Chelsea and Clinton",`10011` = "Chelsea and Clinton",`10020` = "Chelsea and Clinton",`10018` = "Chelsea and Clinton",`10019` = "Chelsea and Clinton",`10036` = "Chelsea and Clinton",
`10029` = "East Harlem",`10035` = "East Harlem",
`10010` = "Gramercy Park and Murray Hill",`10016` = "Gramercy Park and Murray Hill",`10017` = "Gramercy Park and Murray Hill",`10022` = "Gramercy Park and Murray Hill",
`10012` = "Greenwich Village and Soho",`10013` = "Greenwich Village and Sohol",`10014` = "Greenwich Village and Soho",
`10004` = "Lower Manhattan",`10005` = "Lower Manhattan",`10006` = "Lower Manhattan",`10007` = "Lower Manhattan",`10038` = "Lower Manhattan",`10280` = "Lower Manhattan",
`10002` = "Lower East Side",`10003` = "Lower East Side",`10009` = "Lower East Side",
`10021` = "Upper East Side",`10028` = "Upper East Side",`10044` = "Upper East Side",`10065` = "Upper East Side",`10075` = "Upper East Side",`10128` = "Upper East Side",
`10023` = "Upper West Side",`10024` = "Upper West Side",`10025` = "Upper West Side",
`10031` = "Inwood and Washington Heights",`10032` = "Inwood and Washington Heights",`10033` = "Inwood and Washington Heights",`10034` = "Inwood and Washington Heights",`10040` = "Inwood and Washington Heights",
`11361` = "Northeast Queens",`11362` = "Northeast Queens",`11363` = "Northeast Queens",`11364` = "Northeast Queens",
`11354` = "North Queens",`11355` = "North Queens",`11356` = "North Queens",`11357` = "North Queens",`11358` = "North Queens",`11359` = "North Queens",`11360` = "North Queens",
`11365` = "Central Queens",`11366` = "Central Queens",`11367` = "Central Queens",
`11412` = "Jamaica",`11423` = "Jamaica",`11432` = "Jamaica",`11433` = "Jamaica",`11434` = "Jamaica",`11435` = "Jamaica",`11436` = "Jamaica",
`1101` = "Northwest Queens",`11102` = "Northwest Queens",`11103` = "Northwest Queens",`11104` = "Northwest Queens",`11105` = "Northwest Queens",`11106` = "Northwest Queens",
`11374` = "West Central Queens",`11375` = "West Central Queens",`11379` = "West Central Queens",`11385` = "West Central Queens",
`11691` = "Rockaways",`11692` = "Rockaways",`11693` = "Rockaways",`11694` = "Rockaways",`11695` = "Rockaways",`11697` = "Rockaways",
`11004` = "Southeast Queens",`11005` = "Southeast Queens",`11411` = "Southeast Queens",`11413` = "Southeast Queens",`11422` = "Southeast Queens",`11426` = "Southeast Queens",`11427` = "Southeast Queens",`11428` = "Southeast Queens",`11429` = "Southeast Queens",
`11415` = "Southwest Queens",`11416` = "Southwest Queens",`11417` = "Southwest Queens",`11418` = "Southwest Queens",`11419` = "Southwest Queenss",`11420` = "Southwest Queens",`11421` = "Southwest Queens",`11414` = "Southwest Queens",
`11368` = "West Queens",`11369` = "West Queens",`11370` = "West Queens",`11372` = "West Queens",`11373` = "West Queens",`11377` = "West Queens",`11378` = "West Queens",
`10302` = "Port Richmond",`10310` = "Port Richmond",`10303` = "Port Richmond",
`10306` = "South Shore",`10307` = "South Shore",`10308` = "South Shore",`10309` = "South Shore",`10312` = "South Shore",
`10301` = "Stapleton and St. George",`10304` = "Stapleton and St. George",`10305` = "Stapleton and St. George",
`10314` = "Mid-Island"
) 
  ) %>% 
  select(borough, everything()) %>% 
  arrange(borough) %>% 
  drop_na()

## save the result
write.csv(res_acci_count,file = "./large_data/res_acci_count.csv")
```

```{r}
res_acci_countplot = ggplot(res_acci_count, aes(x = res_count, y = acci_count))+
  geom_point(aes(shape = borough,color = location))+
  geom_smooth(size = 0.3)+
  scale_x_continuous(breaks = seq(0,30000,2000))+
  theme(axis.text.x = element_text(size = 8, vjust = 0.5, hjust = 0.5, angle = 45),
        plot.title = element_text(size = 12, colour = "blue"))+
  labs(
    title = "Number of Restaurant VS Number of Accident",
    x  = "Number of Restaurant",
    y = "Number of Accident"
  )

ggplotly(res_acci_countplot)
```


