---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(rvest)
library(readr)
library(viridis)
library(leaflet)
library(RColorBrewer)
```

```{r}
data_2018 = 
  read_csv("./data/2018data.csv") %>% 
  janitor::clean_names() 
newnames = colnames(data_2018) %>% 
  str_replace("number_of_","") 
names(data_2018) = newnames

tidy_data = 
data_2018 %>% 
  mutate(
    date_complete = date 
  ) %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  separate(time, into = c("hour", "minute"), sep = ":") %>%
  select(-zip_code, -location, -on_street_name, -cross_street_name, -off_street_name,-collision_id,-year) %>% 
  rename("vehicle_type" = "vehicle_type_code_1",
          "cause" = "contributing_factor_vehicle_1") %>% 
  mutate( day = as.numeric(day),
          month = as.numeric(month),
          hour = as.numeric(hour),
          minute = as.numeric(minute),
          latitude = replace_na(latitude,0),
          vehicle_type = str_to_lower(vehicle_type)
  ) %>%
  filter( latitude != 0) %>% 
  drop_na(borough)
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
## create input widget
boros = tidy_data %>% distinct(borough) %>% pull()

# selectInput widget
## choose boro
selectInput(
  "boro_choice",   ## inputid!! 
  label = h3("Select boro"),
  choices = boros, selected = "MANHATTAN") ## Manhattan: default selection.

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# ## select input change (print change)
renderPlotly({
  tidy_data %>%
  filter(!is.na(cause) & !(cause %in% 
             c('', 'Unspecified',  'Driver Inattention/Distraction','Other Vehicular','Failure to Yield Right-of-Way')) & borough == input$boro_choice
         ) %>% 
  group_by(cause) %>% 
  summarize(count = n()) %>%
  top_n(10, count) %>% 
  mutate(
    cause = fct_reorder(cause,count)
  ) %>% 
    plot_ly(x = ~cause, y = ~count, color = ~cause, type = "bar")
})

```

### Chart B


Column {data-width=450}
-----------------------------------------------------------------------

### Chart C

```{r}

```

### Chart D

```{r}

```

